//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooBox
{
    using System;
    
    public enum ChangeType : int
    {
        Add = 0,
        ModifyState = 1,
        AddVersion = 2
    }
}
