//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVersion
    {
        public long Id { get; set; }
        public string TimeStamp { get; set; }
        public long DocumentId { get; set; }
        public System.Guid BlobId { get; set; }
        public long ClientId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Blob Blob { get; set; }
        public virtual Client Client { get; set; }
    }
}
