//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder : File
    {
        public Folder()
        {
            this.Editors = new HashSet<Identity>();
            this.Files = new HashSet<File>();
        }
    
    
        public virtual User Owner { get; set; }
        public virtual ICollection<Identity> Editors { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual Folder ShareFolder { get; set; }
    }
}
