//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooBox
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FooBoxEntities : DbContext
    {
        public FooBoxEntities()
            : base("name=FooBoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Identity> Identities { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Blob> Blobs { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Changelist> Changelists { get; set; }
        public virtual DbSet<Change> Changes { get; set; }
    }
}
