//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group : Identity
    {
        public Group()
        {
            this.Users = new HashSet<User>();
        }
    
        public string Description { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
