//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public string Id { get; set; }
        public System.DateTime ExpiryTime { get; set; }
        public long UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
