//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class User : Identity
    {
        public User()
        {
            this.Groups = new HashSet<Group>();
            this.Tokens = new HashSet<Token>();
            this.Clients = new HashSet<Client>();
        }
    
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long QuotaLimit { get; set; }
        public long QuotaCharged { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
    }
}
